-- 1. Body Metrics (for Boditrax CSV)
CREATE TABLE body_metrics (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id),
  scan_date TIMESTAMP WITH TIME ZONE,
  weight FLOAT,
  body_fat_pct FLOAT,
  muscle_mass FLOAT,
  visceral_fat INT,
  metabolic_age INT,
  raw_json JSONB, -- Stores all other specific metrics
  UNIQUE(user_id, scan_date)
);

-- 2. Exercises Table
CREATE TABLE exercises (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  description TEXT,
  image_url TEXT, -- Generated by Nano Banana
  category TEXT CHECK (category IN ('Push', 'Pull', 'Legs', 'Other'))
);

-- 3. Nutrition Journal
CREATE TABLE nutrition_journal (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id),
  meal_name TEXT,
  calories INT,
  protein INT,
  carbs INT,
  fat INT,
  is_recurring BOOLEAN DEFAULT false,
  image_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Workout Logs
CREATE TABLE workout_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id),
  workout_type TEXT CHECK (workout_type IN ('Push 1', 'Pull 1', 'Legs 1', 'Push 2', 'Pull 2', 'Legs 2')),
  completed_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
